server:
  port: 8082
spring:
  application:
    name: cloud-client
  rabbitmq:
    host : 127.0.0.1
    port : 5672
    username : guest
    password : guest

feign:
  hystrix:
    # feign熔断器开关
    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8080/eureka/    #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true         #将IP注册到服务注册中心
#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com:
      cloud:
        client:
          client : debug
